"
Binary Decision Diagram

Bryant, Randal E., _Graph-Based Algorithms for Boolean Function Manipulation_ [PDF](https://apps.dtic.mil/sti/pdfs/ADA470446.pdf). IEEE Transactions on Computers. C-35 (8): 677–691. CiteSeerX 10.1.1.476.2952. doi:10.1109/TC.1986.1676819. S2CID 10385726.  August 1986.

- https://apps.dtic.mil/sti/pdfs/ADA470446.pdf
"
Class {
	#name : 'BDD',
	#superclass : 'DD',
	#category : 'PropositionalLogic',
	#package : 'PropositionalLogic'
}

{ #category : 'truncation and round off' }
BDD >> apply: other [

	self notYetImplemented
]

{ #category : 'truncation and round off' }
BDD >> compose:  x1 and: x2 [

	self notYetImplemented
]

{ #category : 'initialization' }
BDD >> normalize [

	self notYetImplemented
]

{ #category : 'evaluating' }
BDD >> reduce [

	self notYetImplemented
]

{ #category : 'evaluating' }
BDD >> restrict: varIndex [

	self notYetImplemented
]

{ #category : 'evaluating' }
BDD >> satisfyAll [

	self notYetImplemented
]

{ #category : 'evaluating' }
BDD >> satisfyCount [

	self notYetImplemented
]

{ #category : 'evaluating' }
BDD >> satisfyOne [

	self notYetImplemented
]
